[package]
name = "vkrs"
version = "0.1.0"
authors = ["al-9"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.19"
pretty-bytes = "0.2.2"